# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HDF5.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HDF5.proto',
  package='asset',
  syntax='proto3',
  serialized_pb=_b('\n\nHDF5.proto\x12\x05\x61sset\" \n\x0c\x41ssetRequest\x12\x10\n\x08selector\x18\x01 \x01(\t\"\x1d\n\nAssetReply\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\x05\x41sset\x12\x34\n\x08GetAsset\x12\x13.asset.AssetRequest\x1a\x11.asset.AssetReply\"\x00\x42,\n\x16io.grpc.examples.assetB\nAssetProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_ASSETREQUEST = _descriptor.Descriptor(
  name='AssetRequest',
  full_name='asset.AssetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='asset.AssetRequest.selector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=53,
)


_ASSETREPLY = _descriptor.Descriptor(
  name='AssetReply',
  full_name='asset.AssetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='asset.AssetReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['AssetRequest'] = _ASSETREQUEST
DESCRIPTOR.message_types_by_name['AssetReply'] = _ASSETREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssetRequest = _reflection.GeneratedProtocolMessageType('AssetRequest', (_message.Message,), dict(
  DESCRIPTOR = _ASSETREQUEST,
  __module__ = 'HDF5_pb2'
  # @@protoc_insertion_point(class_scope:asset.AssetRequest)
  ))
_sym_db.RegisterMessage(AssetRequest)

AssetReply = _reflection.GeneratedProtocolMessageType('AssetReply', (_message.Message,), dict(
  DESCRIPTOR = _ASSETREPLY,
  __module__ = 'HDF5_pb2'
  # @@protoc_insertion_point(class_scope:asset.AssetReply)
  ))
_sym_db.RegisterMessage(AssetReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026io.grpc.examples.assetB\nAssetProtoP\001\242\002\003HLW'))

_ASSET = _descriptor.ServiceDescriptor(
  name='Asset',
  full_name='asset.Asset',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=86,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAsset',
    full_name='asset.Asset.GetAsset',
    index=0,
    containing_service=None,
    input_type=_ASSETREQUEST,
    output_type=_ASSETREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASSET)

DESCRIPTOR.services_by_name['Asset'] = _ASSET

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class AssetStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetAsset = channel.unary_unary(
          '/asset.Asset/GetAsset',
          request_serializer=AssetRequest.SerializeToString,
          response_deserializer=AssetReply.FromString,
          )


  class AssetServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetAsset(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_AssetServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetAsset': grpc.unary_unary_rpc_method_handler(
            servicer.GetAsset,
            request_deserializer=AssetRequest.FromString,
            response_serializer=AssetReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'asset.Asset', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaAssetServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetAsset(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaAssetStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetAsset(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetAsset.future = None


  def beta_create_Asset_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('asset.Asset', 'GetAsset'): AssetRequest.FromString,
    }
    response_serializers = {
      ('asset.Asset', 'GetAsset'): AssetReply.SerializeToString,
    }
    method_implementations = {
      ('asset.Asset', 'GetAsset'): face_utilities.unary_unary_inline(servicer.GetAsset),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Asset_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('asset.Asset', 'GetAsset'): AssetRequest.SerializeToString,
    }
    response_deserializers = {
      ('asset.Asset', 'GetAsset'): AssetReply.FromString,
    }
    cardinalities = {
      'GetAsset': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'asset.Asset', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
